export const SET_LAYER_VISIBILITY = 'SET_LAYER_VISIBILITY';
export const SET_LOADING_STATUS = 'SET_LOADING_STATUS';
export const GET_RIVER_STATIONS = 'GET_RIVER_STATIONS';
export const GET_DAM_STATIONS = 'GET_DAM_STATIONS';
export const GET_POLLUTION_SOURCES = 'GET_POLLUTION_SOURCES';
export const SET_DEFAULT_LOCATION = 'SET_DEFAULT_LOCATION';
